server:
  port: 8083

spring:
  application:
    name: subscription-service
  datasource:
    url: jdbc:postgresql://postgres:5432/madda_subscription_db
    username: madda_user
    password: madda_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs