server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**
        - id: sourcing-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/sourcing/**
        - id: subscription-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/subscriptions/**, /api/v1/plans/**

jwt:
  secret: ${JWT_SECRET}